### ISSUE TITLE
crc::Table not found with crc 3.4.0 on Windows

### ISSUE THREAD

**Issue by Goldziher** [hasenbanck/lzma-rust2#89]
Hey there,

We're using lzma-rust2 in our project and ran into a compilation failure on Windows when version 0.16.1 resolves to crc 3.4.0. The error is:

```
cannot find type `Table` in crate `crc`
```

It looks like crc 3.4.0 removed or changed the `Table` type that lzma-rust2 relies on. We've worked around it by pinning to 0.15.7 which resolves to crc 3.3.0, but it'd be great if 0.16.x could be updated to work with the latest crc release.

This only seems to affect Windows builds - Linux and macOS compile fine, which makes it a bit tricky to catch.

Thanks for maintaining this crate!

**Comment by hasenbanck** [comment]
Thanks for the report.

This is very odd, since we test compiling under windows: https://github.com/hasenbanck/lzma-rust2/actions/runs/21912262206/job/63269320903

And it builds fine with 3.4!

But we had so many issues now with the crc crate and their breaking change in that minor release, that I'm considering to switching to crc32fast / crc64fast instead by now.

Issues: #76 #77 #78 #86 #87 #88

**Comment by hasenbanck** [comment]
@Goldziher I removed the dependency to the crc crate by providing our own CRC implementation for CRC32 and CRC64_XZ. I pushed v0.16.2 to crates.io. Please test if this fixes the issue on your side.
